steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=$_VITE_API_URL'
      - '--tag'
      - '$_IMAGE'
      - '.'

images:
  - '$_IMAGE'

substitutions:
  _VITE_API_URL: 'http://LOAD_BALANCER_DNS_AQUI'
  _IMAGE: 'us-central1-docker.pkg.dev/PROJECT_ID/ovnis-repo/ovnis-frontend'
